# Define the docker-compose services
version: '3.7'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile

    ports:
      - "80:80"
    volumes:
      - .:/automated-network-scan
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]